name: Deploy QA

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to QA Server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd ${{ secrets.QA_PATH }}
            git pull origin dev
            sudo docker build -t stride100:qa .
            sudo docker stop stride100-qa || true
            sudo docker rm stride100-qa || true
            sudo docker run -d \
              --name stride100-qa \
              --network stride_secure_net \
              --env-file .env.qa \
              -p 3001:3000 \
              --restart unless-stopped \
              stride100:qa